#ifndef SPRITES_HPP
#define SPRITES_HPP

/**
 * Used like NULL is for pointers in g_tile_to_spr.
 */
#define SPR_INVALID 0xFF

enum sprite_ids {
	SPR_GRASS,
	SPR_GROUND,
	SPR_SKY,
	SPR_WATER,
	SPR_HORIZON_WATER,
	SPR_SKY_HORIZON,
	SPR_BIG_CLOUDS,
	SPR_GRID,

	SPR_CAPTAIN_SWORD_IDLE_1,
	SPR_CAPTAIN_SWORD_IDLE_2,
	SPR_CAPTAIN_SWORD_IDLE_3,
	SPR_CAPTAIN_SWORD_IDLE_4,
	SPR_CAPTAIN_SWORD_IDLE_5,

	SPR_CAPTAIN_SWORD_RUN_1,
	SPR_CAPTAIN_SWORD_RUN_2,
	SPR_CAPTAIN_SWORD_RUN_3,
	SPR_CAPTAIN_SWORD_RUN_4,
	SPR_CAPTAIN_SWORD_RUN_5,
	SPR_CAPTAIN_SWORD_RUN_6,

	SPR_CRABBY_IDLE_1,
	SPR_CRABBY_IDLE_2,
	SPR_CRABBY_IDLE_3,
	SPR_CRABBY_IDLE_4,
	SPR_CRABBY_IDLE_5,
	SPR_CRABBY_IDLE_6,
	SPR_CRABBY_IDLE_7,
	SPR_CRABBY_IDLE_8,
	SPR_CRABBY_IDLE_9,

	SPR_CRABBY_RUN_1,
	SPR_CRABBY_RUN_2,
	SPR_CRABBY_RUN_3,
	SPR_CRABBY_RUN_4,
	SPR_CRABBY_RUN_5,
	SPR_CRABBY_RUN_6,

	COUNTOF_SPR
};

extern const char *const g_sprite_files[COUNTOF_SPR];

#endif
